# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b65c55bb45df3affb8d4e440a97834b5060d43a67ad48714455fd18f5933a08cce337eba9d8b059b33551090ee6f812b5a194a27af7bab1bef92a043a5e7be

test:
  secret_key_base: 11be226c2a7dac5ef9ab63930e23bd04e5f62ad37612bc585ce129b2c61994c71b10e02d64e16c75af0be8a121c314bffc8d2ebc46ebf636fea6956adc0178a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
